name: HACS Validate

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: HACS Action
      uses: hacs/action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        category: "integration"